apiVersion: v1
kind: Secret
metadata:
    name: backend-secret
    namespace: ${KUBE_NAMESPACE}
type: Opaque
data:
    backendTokenSecret: ${KUBE_BACKEND_TOKEN_SECRET_B64}
    backendAccessTokenDuration: ${KUBE_BACKEND_ACCESS_TOKEN_DURATION_B64}
    backendRefreshTokenDuration: ${KUBE_BACKEND_REFRESH_TOKEN_DURATION_B64}
    backendDefaultUserFullName: ${KUBE_BACKEND_DEFAULT_USER_FULL_NAME_B64}
    backendDefaultUserEmail: ${KUBE_BACKEND_DEFAULT_USER_EMAIL_B64}
    backendDefaultUserUsername: ${KUBE_BACKEND_DEFAULT_USER_USERNAME_B64}
    backendDefaultUserPassword: ${KUBE_BACKEND_DEFAULT_USER_PASSWORD_B64}
    backendGoogleClientId: ${KUBE_BACKEND_GOOGLE_CLIENT_ID_B64}
    backendGoogleClientSecret: ${KUBE_BACKEND_GOOGLE_CLIENT_SECRET_B64}
    backendGoogleRedirectUrl: ${KUBE_BACKEND_GOOGLE_REDIRECT_URL_B64}
    backendGithubClientId: ${KUBE_BACKEND_GITHUB_CLIENT_ID_B64}
    backendGithubClientSecret: ${KUBE_BACKEND_GITHUB_CLIENT_SECRET_B64}
    backendGithubRedirectUrl: ${KUBE_BACKEND_GITHUB_REDIRECT_URL_B64}

---

apiVersion: v1
kind: Secret
metadata:
    name: frontend-secret
    namespace: ${KUBE_NAMESPACE}
type: Opaque
data:
    frontendUrl: ${KUBE_FRONTEND_URL_B64}
    frontendBackendUrl: ${KUBE_FRONTEND_BACKEND_URL_B64}
    frontendOAuthUrl: ${KUBE_FRONTEND_OAUTH_URL_B64}
    frontendGithubUser: ${KUBE_FRONTEND_GITHUB_USER_B64}
    
---

apiVersion: v1
kind: Secret
metadata:
    name: database-secret
    namespace: ${KUBE_NAMESPACE}
type: Opaque
data:
    databaseName: ${KUBE_DATABASE_NAME_B64}
    databaseUser: ${KUBE_DATABASE_USER_B64}
    databasePassword: ${KUBE_DATABASE_PASSWORD_B64}


---

apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: ${KUBE_NAMESPACE}
type: Opaque
data:
    redisPassword: ${KUBE_REDIS_PASSWORD_B64}

---

apiVersion: v1
kind: Secret
metadata:
    name: storage-secret
    namespace: ${KUBE_NAMESPACE}
type: Opaque
data:
    storageType: ${KUBE_STORAGE_TYPE_B64}
    storageAwsAccessKeyId: ${KUBE_STORAGE_AWS_ACCESS_KEY_ID_B64}
    storageAwsSecretAccessKey: ${KUBE_STORAGE_AWS_SECRET_ACCESS_KEY_B64}
    storageAwsRegion: ${KUBE_STORAGE_AWS_REGION_B64}
    storageAwsBucket: ${KUBE_STORAGE_AWS_BUCKET_B64}
    storageVirusCheckerType: ${KUBE_STORAGE_VIRUS_CHECKER_TYPE_B64}
    storageVirusCheckerApiKey: ${KUBE_STORAGE_VIRUS_CHECKER_API_KEY_B64}
    