apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: ${KUBE_NAMESPACE} 
    name: redis-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: bitnami/valkey:8.0.2
                  imagePullPolicy: "IfNotPresent"
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "75m"
                    limits:
                      memory: "256Mi"
                      cpu: "256m"
                  ports:
                      - containerPort: 6379
                  env:
                      - name: VALKEY_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: redis-secret
                                key: redisPassword

---
apiVersion: v1
kind: Service
metadata:
    namespace: ${KUBE_NAMESPACE}  
    name: redis-service
spec:
    selector:
        app: redis
    ports:
        - port: 6379
    type: ClusterIP