apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: portfolio 
    name: frontend-deployment
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: yoshiunfriendly/frontend-hideyoshi.com:latest
                  imagePullPolicy: "Always"
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "250m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
                  ports:
                      - containerPort: 5000
                  env:
                      - name: PORT
                        value: "5000"
                      - name: BACKEND_URL
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: backendUrl
                      - name: BACKEND_OAUTH_URL
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: backendOAuthUrl

---
apiVersion: v1
kind: Service
metadata:
    namespace: portfolio 
    name: frontend-service
spec:
    selector:
        app: frontend
    ports:
        - port: 5000
          protocol: TCP
          targetPort: 5000
    type: ClusterIP