apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: portfolio
    name: backend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: yoshiunfriendly/backend-hideyoshi.com
                  imagePullPolicy: "Always"
                  ports:
                      - containerPort: 8070
                  env:
                      - name: FRONTEND_PATH
                        valueFrom:
                            configMapKeyRef:
                                name: frontend-config
                                key: frontend_url

                      - name: FRONTEND_CONNECTION_TYPE
                        valueFrom:
                            configMapKeyRef:
                                name: frontend-config
                                key: frontend-type

                      - name: TOKEN_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: token_secret

                      - name: ACCESS_TOKEN_DURATION
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: access_token_duration

                      - name: REFRESH_TOKEN_DURATION
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: refresh_token_duration

                      - name: DEFAULT_USER_FULLNAME
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: default_user_fullname

                      - name: DEFAULT_USER_EMAIL
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: default_user_email

                      - name: DEFAULT_USER_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: default_user_username

                      - name: DEFAULT_USER_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: default_user_password

                      - name: PORT
                        valueFrom:
                            configMapKeyRef:
                                name: backend-config
                                key: backend_port

                      - name: GOOGLE_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: google_client_id

                      - name: GOOGLE_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: google_client_secret

                      - name: GOOGLE_REDIRECT_URL
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: google_redirect_url

                      - name: GITHUB_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: github_client_id

                      - name: GITHUB_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: github_client_secret

                      - name: GITHUB_REDIRECT_URL
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: github_redirect_url

                      - name: POSTGRES_URL
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: postgres_url

                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: postgres_db

                      - name: DATABASE_URL
                        value: "postgresql://$(POSTGRES_URL):5432/$(POSTGRES_DB)"

                      - name: DATABASE_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: postgres_user

                      - name: DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: postgres_password

                      - name: REDIS_URL
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-url

                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-port

                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: redis-secret
                                key: redis-password

---
apiVersion: v1
kind: Service
metadata:
    namespace: portfolio
    name: backend-service
spec:
    selector:
        app: backend
    ports:
        - port: 8070
          protocol: TCP
          targetPort: 8070
    type: ClusterIP
