apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: portfolio
    name: storage-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: storage
    template:
        metadata:
            labels:
                app: storage
        spec:
            nodeSelector:
                node_type: worker
            containers:
                - name: storage
                  image: yoshiunfriendly/storage-hideyoshi.com:latest
                  imagePullPolicy: "Always"
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "256Mi"
                          cpu: "250m"
                  ports:
                      - containerPort: 8000
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 8000
                      initialDelaySeconds: 30
                  env:
                      - name: ALLOWED_ORIGINS
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: backendUrl

                      - name: EXPIRES_IN
                        valueFrom:
                            secretKeyRef:
                                name: backend-secret
                                key: accessTokenDuration

                      - name: SERVER_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: storage-config
                                key: storage_port

                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-url

                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-port

                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: redis-secret
                                key: redisPassword

                      - name: STORAGE_TYPE
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: storageType

                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsAccessKeyId

                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsSecretAccessKey

                      - name: AWS_REGION_NAME
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsRegion

                      - name: AWS_BUCKET_NAME
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsBucket

                      - name: VIRUS_CHECKER_TYPE
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: virusCheckerType

                      - name: VIRUS_CHECKER_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: virusCheckerApiKey

---
apiVersion: v1
kind: Service
metadata:
    namespace: portfolio
    name: storage-service
spec:
    selector:
        app: storage
    ports:
        - port: 8000
          protocol: TCP
          targetPort: 8000
    type: ClusterIP
