apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: portfolio
    name: storage-processor-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: storage-processor
    template:
        metadata:
            labels:
                app: storage-processor
        spec:
            containers:
                - name: storage-processor
                  image: yoshiunfriendly/storage-hideyoshi.com:latest
                  command: [ "./run-queue.sh" ]
                  args: [ "-q" ]
                  imagePullPolicy: "Always"
                  resources:
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
                    limits:
                      memory: "1024Mi"
                      cpu: "500m"
                  env:
                      - name: REDIS_BASE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-url

                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-port

                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: redis-secret
                                key: redisPassword

                      - name: REDIS_URL
                        value: "redis://:$(REDIS_PASSWORD)@$(REDIS_BASE_URL):$(REDIS_PORT)/rq"

                      - name: STORAGE_TYPE
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: storageType

                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsAccessKeyId

                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsSecretAccessKey

                      - name: AWS_REGION_NAME
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsRegion

                      - name: AWS_BUCKET_NAME
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: awsBucket

                      - name: VIRUS_CHECKER_TYPE
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: virusCheckerType

                      - name: VIRUS_CHECKER_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: storage-secret
                                key: virusCheckerApiKey