apiVersion: v1
kind: Secret
metadata:
    namespace: portfolio
    name: storage-secret
type: Opaque
data:
    storage_url: $STORAGE_URL
    storage_type: $STORAGE_TYPE
    aws_access_key_id: $AWS_ACCESS_KEY_ID
    aws_access_access_key: $AWS_SECRET_ACCESS_KEY
    aws_region_name: $AWS_REGION_NAME
    aws_bucket_name: $AWS_BUCKET_NAME