apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: default
    pluginConfig:
    - name: "RemoveDuplicates"
    - name: "RemovePodsViolatingInterPodAntiAffinity"
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "cpu": 55
          "memory": 55
          "pods": 2
        targetThresholds:
          "cpu": 60
          "memory": 60
          "pods": 3
    - name: "RemovePodsHavingTooManyRestarts"
      args:
        podRestartThreshold: 100
        includingInitContainers: true
    plugins:
      deschedule:
        enabled:
          - "RemovePodsViolatingInterPodAntiAffinity"
          - "RemovePodsHavingTooManyRestarts"
      balance:
        enabled:
          - "RemoveDuplicates"
          - "LowNodeUtilization"