apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
    namespace: portfolio
    name: postgres-portfolio-profile
spec:
    cpu: "250m"
    memory: "512Mi"
    containers:
        pg-main-container:
            cpu: "250m"
            memory: "512Mi" 

---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
    namespace: portfolio
    name: postgres-cluster
spec:
    instances: 1
    postgres:
        version: "latest"
    pods:
        persistentVolume:
            size: "5Gi"
    sgInstanceProfile: postgres-portfolio-profile
