apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: letsencrypt-cluster-certificate
    namespace: ${KUBE_NAMESPACE}
spec:
    dnsNames:
        - ${KUBE_DOMAIN}
        - ${KUBE_API_DOMAIN}
    secretName: letsencrypt-cluster-certificate-tls
    issuerRef:
        name: cluster-certificate-issuer
        kind: ClusterIssuer
    subject:
        organizations:
            - ${KUBE_DOMAIN_ORGANIZATION}