apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cluster-certificate-issuer
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: vitor.h.n.batista@gmail.com
        privateKeySecretRef:
            name: cluster-certificate-issuer
        solvers:
            - http01:
                  ingress:
                      class: nginx
