apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: letsencrypt-cluster-certificate
    namespace: portfolio
spec:
    dnsNames:
        - hideyoshi.com.br
        - api.hideyoshi.com.br
    secretName: letsencrypt-cluster-certificate-tls
    issuerRef:
        name: cluster-certificate-issuer
        kind: ClusterIssuer
    subject:
        organizations:
            - Hideyoshi