apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cluster-certificate-issuer
spec:
    acme:
        server: ${KUBE_CERT_SERVER}
        email: ${KUBE_DOMAIN_EMAIL}
        privateKeySecretRef:
            name: cluster-certificate-issuer
        solvers:
            - http01:
                  ingress:
                      class: nginx
