apiVersion: v1
kind: Secret
metadata:
    namespace: portfolio
    name: postgres-secret
type: Opaque
data:
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB