kind: PersistentVolume
apiVersion: v1
metadata:
    namespace: portfolio 
    name: postgres-pv-volume
    labels:
        type: local
        app: postgres
spec:
    storageClassName: manual
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    namespace: portfolio 
    name: postgres-pv-claim
    labels:
        app: postgres
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi