apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: ${KUBE_NAMESPACE}  
    name: frontend-deployment
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            nodeSelector: 
                ${WORKER_NODE_LABEL}
            initContainers:
                - name: wait-backend-init
                  image: busybox:latest
                  args:
                      - /bin/sh
                      - -c
                      - >
                          set -x;
                          while [ $(curl -sw '%{http_code}' "backend-service:8000/health" -o /dev/null) -ne 200 ]; do
                          sleep 15;
                          done
            containers:
                - name: frontend
                  image: yoshiunfriendly/frontend-hideyoshi.com:latest
                  imagePullPolicy: "Always"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "75m"
                      limits:
                          memory: "128Mi"
                          cpu: "75m"
                  ports:
                      - containerPort: 5000
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 5000
                      initialDelaySeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 5000
                      initialDelaySeconds: 10
                  env:
                      - name: PORT
                        value: "5000"
                      - name: BACKEND_URL
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: frontendBackendUrl
                      - name: BACKEND_OAUTH_URL
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: frontendOAuthUrl
                      - name: GITHUB_USER
                        valueFrom:
                            secretKeyRef:
                                name: frontend-secret
                                key: frontendGithubUser

---
apiVersion: v1
kind: Service
metadata:
    namespace: ${KUBE_NAMESPACE}  
    name: frontend-service
spec:
    selector:
        app: frontend
    ports:
        - port: 5000
          protocol: TCP
          targetPort: 5000
    type: ClusterIP
