apiVersion: v1
kind: Secret
metadata:
    namespace: portfolio 
    name: postgres-secret
type: Opaque
data:
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: cG9zdGdyZXM=
    POSTGRES_DB: cG9ydGZvbGlv
