name: remote ssh command

on:
    push:
        branches:
            - staging

jobs:
    build:
        name: Build
        environment: staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"

            - name: Create Config Json File
              run: |
                echo ${{ secrets.CONFIG_JSON }} | base64 -d > config.json

            - name: Inserts Prod Enviromental Variables
              run: |
                python -m pip install --upgrade pip pipenv
                pipenv install
                pipenv run python setup.py -e staging -f config.json

            - name: copy file via ssh
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                source: "."
                target: "infra-hideyoshi.com"

            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  cd infra-hideyoshi.com
                  ./deploy.sh --staging