name: remote ssh command

on:
    push:
        branches:
            - "main"

jobs:
    build:
        name: Build
        environment: prod
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Make Env File
              uses: SpicyPizza/create-envfile@v2.0
              with:
                envkey_FRONTEND_PATH: ${{ secrets.FRONTEND_PATH }}
                envkey_TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
                envkey_ACCESS_TOKEN_DURATION: ${{ secrets.ACCESS_TOKEN_DURATION }}
                envkey_REFRESH_TOKEN_DURATION: ${{ secrets.REFRESH_TOKEN_DURATION }}
                envkey_DEFAULT_USER_FULLNAME: ${{ secrets.DEFAULT_USER_FULLNAME }}
                envkey_DEFAULT_USER_EMAIL: ${{ secrets.DEFAULT_USER_EMAIL }}
                envkey_DEFAULT_USER_USERNAME: ${{ secrets.DEFAULT_USER_USERNAME }}
                envkey_DEFAULT_USER_PASSWORD: ${{ secrets.DEFAULT_USER_PASSWORD }}
                envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                envkey_GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
                envkey_OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
                envkey_OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
                envkey_OAUTH_GITHUB_REDIRECT_URL: ${{ secrets.OAUTH_GITHUB_REDIRECT_URL }}
                envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

            - name: Inserts Prod Enviromental Variables
              run: |
                ./setup.sh --prod .env

            - name: copy file via ssh
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                source: "."
                target: "infra-hideyoshi.com"

            - name: executing remote ssh commands
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  cd infra-hideyoshi.com
                  ./deploy.sh